// Auto-generated imageList
const imageList = [
    "images/abacus1.png",
    "images/accordion1.png",
    "images/airpump1.png",
    "images/airtank1.png",
    "images/alligator1.png",
    "images/anchor1.png",
    "images/antelope1.png",
    "images/apple1.png",
    "images/aquarium1.png",
    "images/arch1.png",
    "images/armchair1.png",
    "images/artichoke1.png",
    "images/axe1.png",
    "images/babyswing1.png",
    "images/bagel1.png",
    "images/balloon1.png",
    "images/banana1.png",
    "images/bandaid1.png",
    "images/barette1.png",
    "images/barrel1.png",
    "images/baseballbat1.png",
    "images/baseballcap1.png",
    "images/basket1.png",
    "images/basketballhoop1.png",
    "images/bat1.png",
    "images/bathtub1.png",
    "images/batteries1.png",
    "images/beanbagchair1.png",
    "images/bear1.png",
    "images/bed1.png",
    "images/bee1.png",
    "images/bell1.png",
    "images/belt1.png",
    "images/bench1.png",
    "images/biceskates1.png",
    "images/bicycle1.png",
    "images/binoculars1.png",
    "images/bishop1.png",
    "images/blender1.png",
    "images/blueberries1.png",
    "images/board1.png",
    "images/bonzai1.png",
    "images/book1.png",
    "images/bookcase1.png",
    "images/bottleopener1.png",
    "images/bowl1.png",
    "images/bowtie1.png",
    "images/box1.png",
    "images/bracelet1.png",
    "images/bread1.png",
    "images/brie1.png",
    "images/briefcase1.png",
    "images/broom1.png",
    "images/buffalo1.png",
    "images/building1.png",
    "images/bulldozer1.png",
    "images/bunkbed1.png",
    "images/bunny1.png",
    "images/bureau1.png",
    "images/bus1.png",
    "images/butterfly1.png",
    "images/button1.png",
    "images/cabinet1.png",
    "images/cactus1.png",
    "images/cake1.png",
    "images/calculator1.png",
    "images/camel1.png",
    "images/camera1.png",
    "images/candle1.png",
    "images/candy1.png",
    "images/candybar1.png",
    "images/candybar2.png",
    "images/candybar3.png",
    "images/candybar4.png",
    "images/cane1.png",
    "images/canoe1.png",
    "images/canopener1.png",
    "images/canteloupe1.png",
    "images/car1.png",
    "images/carabener1.png",
    "images/carrots1.png",
    "images/carseat1.png",
    "images/cart1.png",
    "images/cashregister1.png",
    "images/cat1.png",
    "images/cateringtray1.png",
    "images/cherry1.png",
    "images/chinesefoodbox1.png",
    "images/chisel1.png",
    "images/cigarette1.png",
    "images/clipboard1.png",
    "images/clock1.png",
    "images/clock2.png",
    "images/clock3.png",
    "images/clock4.png",
    "images/clothespin1.png",
    "images/coconut1.png",
    "images/coffeecup1.png",
    "images/coffeemaker1.png",
    "images/coffeepot1.png",
    "images/coin1.png",
    "images/comb1.png",
    "images/compass1.png",
    "images/computer1.png",
    "images/computermouse1.png",
    "images/cone1.png",
    "images/contactscase1.png",
    "images/container1.png",
    "images/cooker1.png",
    "images/cookies1.png",
    "images/cooler1.png",
    "images/couch1.png",
    "images/couger1.png",
    "images/cow1.png",
    "images/crab1.png",
    "images/crayons1.png",
    "images/crib1.png",
    "images/crochethook1.png",
    "images/croissant1.png",
    "images/crutches1.png",
    "images/cupcake1.png",
    "images/cushion1.png",
    "images/cuttingboard1.png",
    "images/deer1.png",
    "images/diapers1.png",
    "images/die1.png",
    "images/dinosaur1.png",
    "images/discman1.png",
    "images/discoball1.png",
    "images/dishwasher1.png",
    "images/dispenser1.png",
    "images/dog1.png",
    "images/dollarbill1.png",
    "images/dolly1.png",
    "images/dolphin1.png",
    "images/domino1.png",
    "images/donut1.png",
    "images/door1.png",
    "images/doorknob1.png",
    "images/dresser1.png",
    "images/dropbottle1.png",
    "images/drum1.png",
    "images/drumset1.png",
    "images/dryer1.png",
    "images/dumpster1.png",
    "images/dustpan1.png",
    "images/earrings1.png",
    "images/earth1.png",
    "images/easel1.png",
    "images/egg1.png",
    "images/eggplant1.png",
    "images/electricbass1.png",
    "images/elephant1.png",
    "images/fan1.png",
    "images/faucet1.png",
    "images/feather1.png",
    "images/filingcabinet1.png",
    "images/fireextinguisher1.png",
    "images/firepit1.png",
    "images/fireplace1.png",
    "images/firetrucktoy1.png",
    "images/fishbowl1.png",
    "images/fishingrod1.png",
    "images/flashlight1.png",
    "images/flask1.png",
    "images/flipflops1.png",
    "images/floppydisk1.png",
    "images/flowerpot1.png",
    "images/folder1.png",
    "images/football1.png",
    "images/fork1.png",
    "images/fork2.png",
    "images/fork3.png",
    "images/fork4.png",
    "images/forklift1.png",
    "images/fortunecookie1.png",
    "images/fourwheeler1.png",
    "images/fox1.png",
    "images/frame1.png",
    "images/frenchfries1.png",
    "images/fridge1.png",
    "images/funnel1.png",
    "images/game1.png",
    "images/gamecontroller1.png",
    "images/gardeninghoe1.png",
    "images/gaspump1.png",
    "images/giftbag1.png",
    "images/giraffe1.png",
    "images/glasses1.png",
    "images/globe1.png",
    "images/glove1.png",
    "images/gnu1.png",
    "images/goggles1.png",
    "images/golfbag1.png",
    "images/golfball1.png",
    "images/golfcart1.png",
    "images/gong1.png",
    "images/gorilla1.png",
    "images/grapes1.png",
    "images/grater1.png",
    "images/grill1.png",
    "images/grinder1.png",
    "images/groundhog1.png",
    "images/guitar1.png",
    "images/hairbrush1.png",
    "images/hairdryer1.png",
    "images/hammer1.png",
    "images/hammock1.png",
    "images/handmirror1.png",
    "images/hanger1.png",
    "images/harmonica1.png",
    "images/harp1.png",
    "images/hat1.png",
    "images/haybale1.png",
    "images/headphones1.png",
    "images/hedgehog1.png",
    "images/helicopter1.png",
    "images/helmet1.png",
    "images/highchair1.png",
    "images/highlighter1.png",
    "images/hippo1.png",
    "images/holepunch1.png",
    "images/honeystick1.png",
    "images/horn1.png",
    "images/horse1.png",
    "images/horseshoe1.png",
    "images/hospitalbed1.png",
    "images/hotairballoon1.png",
    "images/hotdog1.png",
    "images/hourglass1.png",
    "images/hydrant1.png",
    "images/icecream1.png",
    "images/igloo1.png",
    "images/innertube1.png",
    "images/insect1.png",
    "images/iron1.png",
    "images/ironingboard1.png",
    "images/juiceglass1.png",
    "images/kangaroo1.png",
    "images/kayak1.png",
    "images/kazoo1.png",
    "images/key1.png",
    "images/keyboard1.png",
    "images/keyboardkey1.png",
    "images/knife1.png",
    "images/ladder1.png",
    "images/ladybug1.png",
    "images/lamp1.png",
    "images/lantern1.png",
    "images/laptop1.png",
    "images/laundrybasket1.png",
    "images/lawnmower1.png",
    "images/leaf1.png",
    "images/legos1.png",
    "images/lei1.png",
    "images/letter1.png",
    "images/licenseplate1.png",
    "images/lifejacket1.png",
    "images/lifetube1.png",
    "images/lightbulb1.png",
    "images/lighter1.png",
    "images/lighthouse1.png",
    "images/lipstick1.png",
    "images/llama1.png",
    "images/lobster1.png",
    "images/lock1.png",
    "images/lockbox1.png",
    "images/log1.png",
    "images/magnifyingglass1.png",
    "images/mailbox1.png",
    "images/manatee1.png",
    "images/marimba1.png",
    "images/mask1.png",
    "images/matress1.png",
    "images/measuringtape1.png",
    "images/medal1.png",
    "images/medicaltape1.png",
    "images/metalclip1.png",
    "images/meter1.png",
    "images/metronome1.png",
    "images/microscope1.png",
    "images/milkcarton1.png",
    "images/milkshake1.png",
    "images/mitt1.png",
    "images/mixer1.png",
    "images/money1.png",
    "images/moon1.png",
    "images/morterpestle1.png",
    "images/motorcycle1.png",
    "images/muffin1.png",
    "images/mug1.png",
    "images/musicstand1.png",
    "images/musicstand2.png",
    "images/musicstand3.png",
    "images/musicstand4.png",
    "images/nailpolish1.png",
    "images/napkins1.png",
    "images/newspaperstand1.png",
    "images/nozzle1.png",
    "images/olive.png",
    "images/orangutan1.png",
    "images/orca1.png",
    "images/ostrich1.png",
    "images/outhouse1.png",
    "images/oven.png",
    "images/pacifier1.png",
    "images/padlock1.png",
    "images/paintbrush.png",
    "images/palmtree1.png",
    "images/paperclip.png",
    "images/pasta1.png",
    "images/patiotable1.png",
    "images/pear1.png",
    "images/peeler.png",
    "images/pen1.png",
    "images/pencil.png",
    "images/penguin.png",
    "images/pepper1.png",
    "images/peppers1.png",
    "images/pestle.png",
    "images/phone.png",
    "images/phone1.png",
    "images/phoneold.png",
    "images/piano1.png",
    "images/pickle.png",
    "images/picnicbasket.png",
    "images/picnictable1.png",
    "images/pie1.png",
    "images/pig1.png",
    "images/piggybank.png",
    "images/pill1.png",
    "images/pingpongtable1.png",
    "images/pipe1.png",
    "images/pizza1.png",
    "images/plate1.png",
    "images/plate2.png",
    "images/plate3.png",
    "images/plate4.png",
    "images/pliers1.png",
    "images/plunger1.png",
    "images/polarbear.png",
    "images/pooltable.png",
    "images/portapotty1.png",
    "images/pot1.png",
    "images/potato.png",
    "images/potatochips1.png",
    "images/potatomasher1.png",
    "images/potpan.png",
    "images/pretzel.png",
    "images/pumpkinpie.png",
    "images/qtips1.png",
    "images/rabbit1.png",
    "images/racquet.png",
    "images/rainbowslice.png",
    "images/rake1.png",
    "images/razor1.png",
    "images/recordplayer1.png",
    "images/redcabbage.png",
    "images/remote1.png",
    "images/remover1.png",
    "images/rhino.png",
    "images/ring.png",
    "images/rockingchair1.png",
    "images/ruler.png",
    "images/saddle.png",
    "images/safetypin.png",
    "images/santahat1.png",
    "images/scales.png",
    "images/scanner.png",
    "images/schoolbag.png",
    "images/scissors.png",
    "images/scooter1.png",
    "images/scrabble1.png",
    "images/screwdriver1.png",
    "images/scroll1.png",
    "images/scrubber1.png",
    "images/seal1.png",
    "images/sealion1.png",
    "images/seashell1.png",
    "images/seatbelt.png",
    "images/seats.png",
    "images/sewingmachine.png",
    "images/sharpener1.png",
    "images/sheep1.png",
    "images/shelf.png",
    "images/ship1.png",
    "images/shortbread.png",
    "images/skateboard.png",
    "images/skull.png",
    "images/snail.png",
    "images/snowflake.png",
    "images/soapdish1.png",
    "images/soccerball1.png",
    "images/sock.png",
    "images/spiderweb.png",
    "images/spinningwheel1.png",
    "images/spoon.png",
    "images/spraybottle1.png",
    "images/staircase1.png",
    "images/stapler1.png",
    "images/starfish1.png",
    "images/starfish2.png",
    "images/starfish3.png",
    "images/starfish4.png",
    "images/statue1.png",
    "images/statueofliberty1.png",
    "images/stethescope1.png",
    "images/stonehome1.png",
    "images/stoplight.png",
    "images/streetsign1.png",
    "images/streetsweeper1.png",
    "images/string1.png",
    "images/stroller1.png",
    "images/suitcase1.png",
    "images/sunglasses1.png",
    "images/swan.png",
    "images/swan1.png",
    "images/sweater.png",
    "images/swimmingpool.png",
    "images/swimsuit1.png",
    "images/taperoll1.png",
    "images/teabag1.png",
    "images/teacup.png",
    "images/teak1.png",
    "images/teapot1.png",
    "images/telephonebox1.png",
    "images/telescope.png",
    "images/tent.png",
    "images/ticketstub1.png",
    "images/tiger.png",
    "images/tire1.png",
    "images/tire2.png",
    "images/tire3.png",
    "images/tire4.png",
    "images/toilet.png",
    "images/toiletpaper1.png",
    "images/toiletseat1.png",
    "images/tomato.png",
    "images/tombstone1.png",
    "images/tongs1.png",
    "images/toothbrush1.png",
    "images/toy1.png",
    "images/toyhand1.png",
    "images/toykeys1.png",
    "images/toyplane1.png",
    "images/toywrench1.png",
    "images/tractor1.png",
    "images/train1.png",
    "images/trashcan.png",
    "images/treadmill1.png",
    "images/tricycle1.png",
    "images/trophy1.png",
    "images/trowel1.png",
    "images/trumpet1.png",
    "images/trunk.png",
    "images/tube1.png",
    "images/turkey.png",
    "images/turtle1.png",
    "images/tweezers1.png",
    "images/tweezers2.png",
    "images/tweezers3.png",
    "images/tweezers4.png",
    "images/typewriter1.png",
    "images/umbrella1.png",
    "images/vacuum1.png",
    "images/vendingmachine.png",
    "images/waffleiron.png",
    "images/waffleiron1.png",
    "images/walker1.png",
    "images/walkytalky1.png",
    "images/walrus1.png",
    "images/washer1.png",
    "images/washer2.png",
    "images/washer3.png",
    "images/washer4.png",
    "images/watch1.png",
    "images/wateringcan1.png",
    "images/waterjug1.png",
    "images/weddingdress1.png",
    "images/whale1.png",
    "images/wheelbarrow1.png",
    "images/wheelbarrow2.png",
    "images/wheelbarrow3.png",
    "images/wheelbarrow4.png",
    "images/wheelchair1.png",
    "images/wheelchair2.png",
    "images/wheelchair3.png",
    "images/wheelchair4.png",
    "images/windmill1.png",
    "images/wineglass1.png",
    "images/wishwell1.png",
    "images/yacht1.png",
    "images/yarn1.png",
    "images/zebra1.png"
];



const categoryPlurals = {
    'abacus': 'abacuses',
    'accordion': 'accordions',
    'airpump': 'air pumps',
    'airtank': 'air tanks',
    'alligator': 'alligators',
    'anchor': 'anchors',
    'antelope': 'antelopes',
    'apple': 'apples',
    'aquarium': 'aquariums',
    'arch': 'arches',
    'armchair': 'armchairs',
    'artichoke': 'artichokes',
    'axe': 'axes',
    'babyswing': 'baby swings',
    'bagel': 'bagels',
    'balloon': 'balloons',
    'banana': 'bananas',
    'bandaid': 'band-aids',
    'barette': 'barrettes',
    'barrel': 'barrels',
    'baseballbat': 'baseball bats',
    'baseballcap': 'baseball caps',
    'basket': 'baskets',
    'basketballhoop': 'basketball hoops',
    'bat': 'bats',
    'bathtub': 'bathtubs',
    'batteries': 'batteries',
    'beanbagchair': 'bean bag chairs',
    'bear': 'bears',
    'bed': 'beds',
    'bee': 'bees',
    'bell': 'bells',
    'belt': 'belts',
    'bench': 'benches',
    'biceskates': 'ice skates',
    'bicycle': 'bicycles',
    'binoculars': 'binoculars',
    'bishop': 'bishops',
    'blender': 'blenders',
    'blueberries': 'blueberries',
    'board': 'boards',
    'bonzai': 'bonsai',
    'book': 'books',
    'bookcase': 'bookcases',
    'bottleopener': 'bottle openers',
    'bowl': 'bowls',
    'bowtie': 'bow ties',
    'box': 'boxes',
    'bracelet': 'bracelets',
    'bread': 'breads',
    'brie': 'brie',
    'briefcase': 'briefcases',
    'broom': 'brooms',
    'buffalo': 'buffalo',
    'building': 'buildings',
    'bulldozer': 'bulldozers',
    'bunkbed': 'bunk beds',
    'bunny': 'bunnies',
    'bureau': 'bureaus',
    'bus': 'buses',
    'butterfly': 'butterflies',
    'button': 'buttons',
    'cabinet': 'cabinets',
    'cactus': 'cacti',
    'cake': 'cakes',
    'calculator': 'calculators',
    'camel': 'camels',
    'camera': 'cameras',
    'candle': 'candles',
    'candy': 'candies',
    'candybar': 'candy bars',
    'cane': 'canes',
    'canoe': 'canoes',
    'canopener': 'can openers',
    'canteloupe': 'cantaloupes',
    'car': 'cars',
    'carabener': 'carabiners',
    'carrots': 'carrots',
    'carseat': 'car seats',
    'cart': 'carts',
    'cashregister': 'cash registers',
    'cat': 'cats',
    'cateringtray': 'catering trays',
    'cherry': 'cherries',
    'chinesefoodbox': 'Chinese food boxes',
    'chisel': 'chisels',
    'cigarette': 'cigarettes',
    'clipboard': 'clipboards',
    'clock': 'clocks',
    'clothespin': 'clothespins',
    'coconut': 'coconuts',
    'coffeecup': 'coffee cups',
    'coffeemaker': 'coffee makers',
    'coffeepot': 'coffee pots',
    'coin': 'coins',
    'comb': 'combs',
    'compass': 'compasses',
    'computer': 'computers',
    'computermouse': 'computer mice',
    'cone': 'cones',
    'contactscase': 'contacts cases',
    'container': 'containers',
    'cooker': 'cookers',
    'cookies': 'cookies',
    'cooler': 'coolers',
    'couch': 'couches',
    'couger': 'cougars',
    'cow': 'cows',
    'crab': 'crabs',
    'crayons': 'crayons',
    'crib': 'cribs',
    'crochethook': 'crochet hooks',
    'croissant': 'croissants',
    'crutches': 'crutches',
    'cupcake': 'cupcakes',
    'cushion': 'cushions',
    'cuttingboard': 'cutting boards',
    'deer': 'deer',
    'diapers': 'diapers',
    'die': 'dice',
    'dinosaur': 'dinosaurs',
    'discman': 'discmans',
    'discoball': 'disco balls',
    'dishwasher': 'dishwashers',
    'dispenser': 'dispensers',
    'dog': 'dogs',
    'dollarbill': 'dollar bills',
    'dolly': 'dollies',
    'dolphin': 'dolphins',
    'domino': 'dominoes',
    'donut': 'donuts',
    'door': 'doors',
    'doorknob': 'doorknobs',
    'dresser': 'dressers',
    'dropbottle': 'drop bottles',
    'drum': 'drums',
    'drumset': 'drum sets',
    'dryer': 'dryers',
    'dumpster': 'dumpsters',
    'dustpan': 'dustpans',
    'earrings': 'earrings',
    'earth': 'earths',
    'easel': 'easels',
    'egg': 'eggs',
    'eggplant': 'eggplants',
    'electricbass': 'electric basses',
    'elephant': 'elephants',
    'fan': 'fans',
    'faucet': 'faucets',
    'feather': 'feathers',
    'filingcabinet': 'filing cabinets',
    'fireextinguisher': 'fire extinguishers',
    'firepit': 'fire pits',
    'fireplace': 'fireplaces',
    'firetrucktoy': 'fire truck toys',
    'fishbowl': 'fishbowls',
    'fishingrod': 'fishing rods',
    'flashlight': 'flashlights',
    'flask': 'flasks',
    'flipflops': 'flip flops',
    'floppydisk': 'floppy disks',
    'flowerpot': 'flower pots',
    'folder': 'folders',
    'football': 'footballs',
    'fork': 'forks',
    'forklift': 'forklifts',
    'fortunecookie': 'fortune cookies',
    'fourwheeler': 'four wheelers',
    'fox': 'foxes',
    'frame': 'frames',
    'frenchfries': 'french fries',
    'fridge': 'fridges',
    'funnel': 'funnels',
    'game': 'games',
    'gamecontroller': 'game controllers',
    'gardeninghoe': 'gardening hoes',
    'gaspump': 'gas pumps',
    'giftbag': 'gift bags',
    'giraffe': 'giraffes',
    'glasses': 'glasses',
    'globe': 'globes',
    'glove': 'gloves',
    'gnu': 'gnus',
    'goggles': 'goggles',
    'golfbag': 'golf bags',
    'golfball': 'golf balls',
    'golfcart': 'golf carts',
    'gong': 'gongs',
    'gorilla': 'gorillas',
    'grapes': 'grapes',
    'grater': 'graters',
    'grill': 'grills',
    'grinder': 'grinders',
    'groundhog': 'groundhogs',
    'guitar': 'guitars',
    'hairbrush': 'hairbrushes',
    'hairdryer': 'hair dryers',
    'hammer': 'hammers',
    'hammock': 'hammocks',
    'handmirror': 'hand mirrors',
    'hanger': 'hangers',
    'harmonica': 'harmonicas',
    'harp': 'harps',
    'hat': 'hats',
    'haybale': 'hay bales',
    'headphones': 'headphones',
    'hedgehog': 'hedgehogs',
    'helicopter': 'helicopters',
    'helmet': 'helmets',
    'highchair': 'high chairs',
    'highlighter': 'highlighters',
    'hippo': 'hippos',
    'holepunch': 'hole punches',
    'honeystick': 'honey sticks',
    'horn': 'horns',
    'horse': 'horses',
    'horseshoe': 'horseshoes',
    'hospitalbed': 'hospital beds',
    'hotairballoon': 'hot air balloons',
    'hotdog': 'hot dogs',
    'hourglass': 'hourglasses',
    'hydrant': 'hydrants',
    'icecream': 'ice creams',
    'igloo': 'igloos',
    'innertube': 'inner tubes',
    'insect': 'insects',
    'iron': 'irons',
    'ironingboard': 'ironing boards',
    'juiceglass': 'juice glasses',
    'kangaroo': 'kangaroos',
    'kayak': 'kayaks',
    'kazoo': 'kazoos',
    'key': 'keys',
    'keyboard': 'keyboards',
    'keyboardkey': 'keyboard keys',
    'knife': 'knives',
    'ladder': 'ladders',
    'ladybug': 'ladybugs',
    'lamp': 'lamps',
    'lantern': 'lanterns',
    'laptop': 'laptops',
    'laundrybasket': 'laundry baskets',
    'lawnmower': 'lawn mowers',
    'leaf': 'leaves',
    'legos': 'legos',
    'lei': 'leis',
    'letter': 'letters',
    'licenseplate': 'license plates',
    'lifejacket': 'life jackets',
    'lifetube': 'life tubes',
    'lightbulb': 'light bulbs',
    'lighter': 'lighters',
    'lighthouse': 'lighthouses',
    'lipstick': 'lipsticks',
    'llama': 'llamas',
    'lobster': 'lobsters',
    'lock': 'locks',
    'lockbox': 'lockboxes',
    'log': 'logs',
    'magnifyingglass': 'magnifying glasses',
    'mailbox': 'mailboxes',
    'manatee': 'manatees',
    'marimba': 'marimbas',
    'mask': 'masks',
    'matress': 'mattresses',
    'measuringtape': 'measuring tapes',
    'medal': 'medals',
    'medicaltape': 'medical tapes',
    'metalclip': 'metal clips',
    'meter': 'meters',
    'metronome': 'metronomes',
    'microscope': 'microscopes',
    'milkcarton': 'milk cartons',
    'milkshake': 'milkshakes',
    'mitt': 'mitts',
    'mixer': 'mixers',
    'money': 'money',
    'moon': 'moons',
    'morterpestle': 'mortar and pestles',
    'motorcycle': 'motorcycles',
    'muffin': 'muffins',
    'mug': 'mugs',
    'musicstand': 'music stands',
    'nailpolish': 'nail polishes',
    'napkins': 'napkins',
    'newspaperstand': 'newspaper stands',
    'nozzle': 'nozzles',
    'olive': 'olives',
    'orangutan': 'orangutans',
    'orca': 'orcas',
    'ostrich': 'ostriches',
    'outhouse': 'outhouses',
    'oven': 'ovens',
    'pacifier': 'pacifiers',
    'padlock': 'padlocks',
    'paintbrush': 'paintbrushes',
    'palmtree': 'palm trees',
    'paperclip': 'paper clips',
    'pasta': 'pastas',
    'patiotable': 'patio tables',
    'pear': 'pears',
    'peeler': 'peelers',
    'pen': 'pens',
    'pencil': 'pencils',
    'penguin': 'penguins',
    'pepper': 'peppers',
    'peppers': 'peppers',
    'pestle': 'pestles',
    'phone': 'phones',
    'phoneold': 'old phones',
    'piano': 'pianos',
    'pickle': 'pickles',
    'picnicbasket': 'picnic baskets',
    'picnictable': 'picnic tables',
    'pie': 'pies',
    'pig': 'pigs',
    'piggybank': 'piggy banks',
    'pill': 'pills',
    'pingpongtable': 'ping pong tables',
    'pipe': 'pipes',
    'pizza': 'pizzas',
    'plate': 'plates',
    'pliers': 'pliers',
    'plunger': 'plungers',
    'polarbear': 'polar bears',
    'pooltable': 'pool tables',
    'portapotty': 'porta potties',
    'pot': 'pots',
    'potato': 'potatoes',
    'potatochips': 'potato chips',
    'potatomasher': 'potato mashers',
    'potpan': 'pot pans',
    'pretzel': 'pretzels',
    'pumpkinpie': 'pumpkin pies',
    'qtips': 'q-tips',
    'rabbit': 'rabbits',
    'racquet': 'racquets',
    'rainbowslice': 'rainbow slices',
    'rake': 'rakes',
    'razor': 'razors',
    'recordplayer': 'record players',
    'redcabbage': 'red cabbages',
    'remote': 'remotes',
    'remover': 'removers',
    'rhino': 'rhinos',
    'ring': 'rings',
    'rockingchair': 'rocking chairs',
    'ruler': 'rulers',
    'saddle': 'saddles',
    'safetypin': 'safety pins',
    'santahat': 'santa hats',
    'scales': 'scales',
    'scanner': 'scanners',
    'schoolbag': 'school bags',
    'scissors': 'scissors',
    'scooter': 'scooters',
    'scrabble': 'scrabbles',
    'screwdriver': 'screwdrivers',
    'scroll': 'scrolls',
    'scrubber': 'scrubbers',
    'seal': 'seals',
    'sealion': 'sea lions',
    'seashell': 'seashells',
    'seatbelt': 'seatbelts',
    'seats': 'seats',
    'sewingmachine': 'sewing machines',
    'sharpener': 'sharpeners',
    'sheep': 'sheep',
    'shelf': 'shelves',
    'ship': 'ships',
    'shortbread': 'shortbreads',
    'skateboard': 'skateboards',
    'skull': 'skulls',
    'snail': 'snails',
    'snowflake': 'snowflakes',
    'soapdish': 'soap dishes',
    'soccerball': 'soccer balls',
    'sock': 'socks',
    'spiderweb': 'spider webs',
    'spinningwheel': 'spinning wheels',
    'spoon': 'spoons',
    'spraybottle': 'spray bottles',
    'staircase': 'staircases',
    'stapler': 'staplers',
    'starfish': 'starfish',
    'statue': 'statues',
    'statueofliberty': 'statues of liberty',
    'stethescope': 'stethoscopes',
    'stonehome': 'stone homes',
    'stoplight': 'stoplights',
    'streetsign': 'street signs',
    'streetsweeper': 'street sweepers',
    'string': 'strings',
    'stroller': 'strollers',
    'suitcase': 'suitcases',
    'sunglasses': 'sunglasses',
    'swan': 'swans',
    'sweater': 'sweaters',
    'swimmingpool': 'swimming pools',
    'swimsuit': 'swimsuits',
    'taperoll': 'tape rolls',
    'teabag': 'tea bags',
    'teacup': 'teacups',
    'teak': 'teaks',
    'teapot': 'teapots',
    'telephonebox': 'telephone boxes',
    'telescope': 'telescopes',
    'tent': 'tents',
    'ticketstub': 'ticket stubs',
    'tiger': 'tigers',
    'tire': 'tires',
    'toilet': 'toilets',
    'toiletpaper': 'toilet papers',
    'toiletseat': 'toilet seats',
    'tomato': 'tomatoes',
    'tombstone': 'tombstones',
    'tongs': 'tongs',
    'toothbrush': 'toothbrushes',
    'toy': 'toys',
    'toyhand': 'toy hands',
    'toykeys': 'toy keys',
    'toyplane': 'toy planes',
    'toywrench': 'toy wrenches',
    'tractor': 'tractors',
    'train': 'trains',
    'trashcan': 'trash cans',
    'treadmill': 'treadmills',
    'tricycle': 'tricycles',
    'trophy': 'trophies',
    'trowel': 'trowels',
    'trumpet': 'trumpets',
    'trunk': 'trunks',
    'tube': 'tubes',
    'turkey': 'turkeys',
    'turtle': 'turtles',
    'tweezers': 'tweezers',
    'typewriter': 'typewriters',
    'umbrella': 'umbrellas',
    'vacuum': 'vacuums',
    'vendingmachine': 'vending machines',
    'waffleiron': 'waffle irons',
    'walker': 'walkers',
    'walkytalky': 'walkie-talkies',
    'walrus': 'walruses',
    'washer': 'washers',
    'watch': 'watches',
    'wateringcan': 'watering cans',
    'waterjug': 'water jugs',
    'weddingdress': 'wedding dresses',
    'whale': 'whales',
    'wheelbarrow': 'wheelbarrows',
    'wheelchair': 'wheelchairs',
    'windmill': 'windmills',
    'wineglass': 'wine glasses',
    'wishwell': 'wishing wells',
    'yacht': 'yachts',
    'yarn': 'yarns',
    'zebra': 'zebras'
};

    const categoryMappings = {
        'abacus': 'abacus',
        'accordion': 'accordion',
        'airpump': 'air pump',
        'airtank': 'air tank',
        'alligator': 'alligator',
        'anchor': 'anchor',
        'antelope': 'antelope',
        'apple': 'apple',
        'aquarium': 'aquarium',
        'arch': 'arch',
        'armchair': 'armchair',
        'artichoke': 'artichoke',
        'axe': 'axe',
        'babyswing': 'baby swing',
        'bagel': 'bagel',
        'balloon': 'balloon',
        'banana': 'banana',
        'bandaid': 'band-aid',
        'barette': 'barrette',
        'barrel': 'barrel',
        'baseballbat': 'baseball bat',
        'baseballcap': 'baseball cap',
        'basket': 'basket',
        'basketballhoop': 'basketball hoop',
        'bat': 'bat',
        'bathtub': 'bathtub',
        'batteries': 'battery',
        'beanbagchair': 'bean bag chair',
        'bear': 'bear',
        'bed': 'bed',
        'bee': 'bee',
        'bell': 'bell',
        'belt': 'belt',
        'bench': 'bench',
        'biceskates': 'ice skates',
        'bicycle': 'bicycle',
        'binoculars': 'binoculars',
        'bishop': 'bishop',
        'blender': 'blender',
        'blueberries': 'blueberry',
        'board': 'board',
        'bonzai': 'bonsai',
        'book': 'book',
        'bookcase': 'bookcase',
        'bottleopener': 'bottle opener',
        'bowl': 'bowl',
        'bowtie': 'bow tie',
        'box': 'box',
        'bracelet': 'bracelet',
        'bread': 'bread',
        'brie': 'brie',
        'briefcase': 'briefcase',
        'broom': 'broom',
        'buffalo': 'buffalo',
        'building': 'building',
        'bulldozer': 'bulldozer',
        'bunkbed': 'bunk bed',
        'bunny': 'bunny',
        'bureau': 'bureau',
        'bus': 'bus',
        'butterfly': 'butterfly',
        'button': 'button',
        'cabinet': 'cabinet',
        'cactus': 'cactus',
        'cake': 'cake',
        'calculator': 'calculator',
        'camel': 'camel',
        'camera': 'camera',
        'candle': 'candle',
        'candy': 'candy',
        'candybar': 'candy bar',
        'cane': 'cane',
        'canoe': 'canoe',
        'canopener': 'can opener',
        'canteloupe': 'cantaloupe',
        'car': 'car',
        'carabener': 'carabiner',
        'carrots': 'carrot',
        'carseat': 'car seat',
        'cart': 'cart',
        'cashregister': 'cash register',
        'cat': 'cat',
        'cateringtray': 'catering tray',
        'cherry': 'cherry',
        'chinesefoodbox': 'Chinese food box',
        'chisel': 'chisel',
        'cigarette': 'cigarette',
        'clipboard': 'clipboard',
        'clock': 'clock',
        'clothespin': 'clothespin',
        'coconut': 'coconut',
        'coffeecup': 'coffee cup',
        'coffeemaker': 'coffee maker',
        'coffeepot': 'coffee pot',
        'coin': 'coin',
        'comb': 'comb',
        'compass': 'compass',
        'computer': 'computer',
        'computermouse': 'computer mouse',
        'cone': 'cone',
        'contactscase': 'contacts case',
        'container': 'container',
        'cooker': 'cooker',
        'cookies': 'cookie',
        'cooler': 'cooler',
        'couch': 'couch',
        'couger': 'cougar',
        'cow': 'cow',
        'crab': 'crab',
        'crayons': 'crayon',
        'crib': 'crib',
        'crochethook': 'crochet hook',
        'croissant': 'croissant',
        'crutches': 'crutch',
        'cupcake': 'cupcake',
        'cushion': 'cushion',
        'cuttingboard': 'cutting board',
        'deer': 'deer',
        'diapers': 'diaper',
        'die': 'die',
        'dinosaur': 'dinosaur',
        'discman': 'discman',
        'discoball': 'disco ball',
        'dishwasher': 'dishwasher',
        'dispenser': 'dispenser',
        'dog': 'dog',
        'dollarbill': 'dollar bill',
        'dolly': 'dolly',
        'dolphin': 'dolphin',
        'domino': 'domino',
        'donut': 'donut',
        'door': 'door',
        'doorknob': 'doorknob',
        'dresser': 'dresser',
        'dropbottle': 'drop bottle',
        'drum': 'drum',
        'drumset': 'drum set',
        'dryer': 'dryer',
        'dumpster': 'dumpster',
        'dustpan': 'dustpan',
        'earrings': 'earring',
        'earth': 'earth',
        'easel': 'easel',
        'egg': 'egg',
        'eggplant': 'eggplant',
        'electricbass': 'electric bass',
        'elephant': 'elephant',
        'fan': 'fan',
        'faucet': 'faucet',
        'feather': 'feather',
        'filingcabinet': 'filing cabinet',
        'fireextinguisher': 'fire extinguisher',
        'firepit': 'fire pit',
        'fireplace': 'fireplace',
        'firetrucktoy': 'fire truck toy',
        'fishbowl': 'fishbowl',
        'fishingrod': 'fishing rod',
        'flashlight': 'flashlight',
        'flask': 'flask',
        'flipflops': 'flip flop',
        'floppydisk': 'floppy disk',
        'flowerpot': 'flower pot',
        'folder': 'folder',
        'football': 'football',
        'fork': 'fork',
        'forklift': 'forklift',
        'fortunecookie': 'fortune cookie',
        'fourwheeler': 'four wheeler',
        'fox': 'fox',
        'frame': 'frame',
        'frenchfries': 'french fries',
        'fridge': 'fridge',
        'funnel': 'funnel',
        'game': 'game',
        'gamecontroller': 'game controller',
        'gardeninghoe': 'gardening hoe',
        'gaspump': 'gas pump',
        'giftbag': 'gift bag',
        'giraffe': 'giraffe',
        'glasses': 'glasses',
        'globe': 'globe',
        'glove': 'glove',
        'gnu': 'gnu',
        'goggles': 'goggles',
        'golfbag': 'golf bag',
        'golfball': 'golf ball',
        'golfcart': 'golf cart',
        'gong': 'gong',
        'gorilla': 'gorilla',
        'grapes': 'grapes',
        'grater': 'grater',
        'grill': 'grill',
        'grinder': 'grinder',
        'groundhog': 'groundhog',
        'guitar': 'guitar',
        'hairbrush': 'hairbrush',
        'hairdryer': 'hair dryer',
        'hammer': 'hammer',
        'hammock': 'hammock',
        'handmirror': 'hand mirror',
        'hanger': 'hanger',
        'harmonica': 'harmonica',
        'harp': 'harp',
        'hat': 'hat',
        'haybale': 'hay bale',
        'headphones': 'headphones',
        'hedgehog': 'hedgehog',
        'helicopter': 'helicopter',
        'helmet': 'helmet',
        'highchair': 'high chair',
        'highlighter': 'highlighter',
        'hippo': 'hippo',
        'holepunch': 'hole punch',
        'honeystick': 'honey stick',
        'horn': 'horn',
        'horse': 'horse',
        'horseshoe': 'horseshoe',
        'hospitalbed': 'hospital bed',
        'hotairballoon': 'hot air balloon',
        'hotdog': 'hot dog',
        'hourglass': 'hourglass',
        'hydrant': 'hydrant',
        'icecream': 'ice cream',
        'igloo': 'igloo',
        'innertube': 'inner tube',
        'insect': 'insect',
        'iron': 'iron',
        'ironingboard': 'ironing board',
        'juiceglass': 'juice glass',
        'kangaroo': 'kangaroo',
        'kayak': 'kayak',
        'kazoo': 'kazoo',
        'key': 'key',
        'keyboard': 'keyboard',
        'keyboardkey': 'keyboard key',
        'knife': 'knife',
        'ladder': 'ladder',
        'ladybug': 'ladybug',
        'lamp': 'lamp',
        'lantern': 'lantern',
        'laptop': 'laptop',
        'laundrybasket': 'laundry basket',
        'lawnmower': 'lawn mower',
        'leaf': 'leaf',
        'legos': 'lego',
        'lei': 'lei',
        'letter': 'letter',
        'licenseplate': 'license plate',
        'lifejacket': 'life jacket',
        'lifetube': 'life tube',
        'lightbulb': 'light bulb',
        'lighter': 'lighter',
        'lighthouse': 'lighthouse',
        'lipstick': 'lipstick',
        'llama': 'llama',
        'lobster': 'lobster',
        'lock': 'lock',
        'lockbox': 'lockbox',
        'log': 'log',
        'magnifyingglass': 'magnifying glass',
        'mailbox': 'mailbox',
        'manatee': 'manatee',
        'marimba': 'marimba',
        'mask': 'mask',
        'matress': 'mattress',
        'measuringtape': 'measuring tape',
        'medal': 'medal',
        'medicaltape': 'medical tape',
        'metalclip': 'metal clip',
        'meter': 'meter',
        'metronome': 'metronome',
        'microscope': 'microscope',
        'milkcarton': 'milk carton',
        'milkshake': 'milkshake',
        'mitt': 'mitt',
        'mixer': 'mixer',
        'money': 'money',
        'moon': 'moon',
        'morterpestle': 'mortar and pestle',
        'motorcycle': 'motorcycle',
        'muffin': 'muffin',
        'mug': 'mug',
        'musicstand': 'music stand',
        'nailpolish': 'nail polish',
        'napkins': 'napkin',
        'newspaperstand': 'newspaper stand',
        'nozzle': 'nozzle',
        'olive': 'olive',
        'orangutan': 'orangutan',
        'orca': 'orca',
        'ostrich': 'ostrich',
        'outhouse': 'outhouse',
        'oven': 'oven',
        'pacifier': 'pacifier',
        'padlock': 'padlock',
        'paintbrush': 'paintbrush',
        'palmtree': 'palm tree',
        'paperclip': 'paper clip',
        'pasta': 'pasta',
        'patiotable': 'patio table',
        'pear': 'pear',
        'peeler': 'peeler',
        'pen': 'pen',
        'pencil': 'pencil',
        'penguin': 'penguin',
        'pepper': 'pepper',
        'peppers': 'pepper',
        'pestle': 'pestle',
        'phone': 'phone',
        'phoneold': 'old phone',
        'piano': 'piano',
        'pickle': 'pickle',
        'picnicbasket': 'picnic basket',
        'picnictable': 'picnic table',
        'pie': 'pie',
        'pig': 'pig',
        'piggybank': 'piggy bank',
        'pill': 'pill',
        'pingpongtable': 'ping pong table',
        'pipe': 'pipe',
        'pizza': 'pizza',
        'plate': 'plate',
        'pliers': 'pliers',
        'plunger': 'plunger',
        'polarbear': 'polar bear',
        'pooltable': 'pool table',
        'portapotty': 'porta potty',
        'pot': 'pot',
        'potato': 'potato',
        'potatochips': 'potato chips',
        'potatomasher': 'potato masher',
        'potpan': 'pot pan',
        'pretzel': 'pretzel',
        'pumpkinpie': 'pumpkin pie',
        'qtips': 'q-tip',
        'rabbit': 'rabbit',
        'racquet': 'racquet',
        'rainbowslice': 'rainbow slice',
        'rake': 'rake',
        'razor': 'razor',
        'recordplayer': 'record player',
        'redcabbage': 'red cabbage',
        'remote': 'remote',
        'remover': 'remover',
        'rhino': 'rhino',
        'ring': 'ring',
        'rockingchair': 'rocking chair',
        'ruler': 'ruler',
        'saddle': 'saddle',
        'safetypin': 'safety pin',
        'santahat': 'santa hat',
        'scales': 'scale',
        'scanner': 'scanner',
        'schoolbag': 'school bag',
        'scissors': 'scissors',
        'scooter': 'scooter',
        'scrabble': 'scrabble',
        'screwdriver': 'screwdriver',
        'scroll': 'scroll',
        'scrubber': 'scrubber',
        'seal': 'seal',
        'sealion': 'sea lion',
        'seashell': 'seashell',
        'seatbelt': 'seatbelt',
        'seats': 'seat',
        'sewingmachine': 'sewing machine',
        'sharpener': 'sharpener',
        'sheep': 'sheep',
        'shelf': 'shelf',
        'ship': 'ship',
        'shortbread': 'shortbread',
        'skateboard': 'skateboard',
        'skull': 'skull',
        'snail': 'snail',
        'snowflake': 'snowflake',
        'soapdish': 'soap dish',
        'soccerball': 'soccer ball',
        'sock': 'sock',
        'spiderweb': 'spider web',
        'spinningwheel': 'spinning wheel',
        'spoon': 'spoon',
        'spraybottle': 'spray bottle',
        'staircase': 'staircase',
        'stapler': 'stapler',
        'starfish': 'starfish',
        'statue': 'statue',
        'statueofliberty': 'statue of liberty',
        'stethescope': 'stethoscope',
        'stonehome': 'stone home',
        'stoplight': 'stoplight',
        'streetsign': 'street sign',
        'streetsweeper': 'street sweeper',
        'string': 'string',
        'stroller': 'stroller',
        'suitcase': 'suitcase',
        'sunglasses': 'sunglasses',
        'swan': 'swan',
        'sweater': 'sweater',
        'swimmingpool': 'swimming pool',
        'swimsuit': 'swimsuit',
        'taperoll': 'tape roll',
        'teabag': 'tea bag',
        'teacup': 'teacup',
        'teak': 'teak',
        'teapot': 'teapot',
        'telephonebox': 'telephone box',
        'telescope': 'telescope',
        'tent': 'tent',
        'ticketstub': 'ticket stub',
        'tiger': 'tiger',
        'tire': 'tire',
        'toilet': 'toilet',
        'toiletpaper': 'toilet paper',
        'toiletseat': 'toilet seat',
        'tomato': 'tomato',
        'tombstone': 'tombstone',
        'tongs': 'tongs',
        'toothbrush': 'toothbrush',
        'toy': 'toy',
        'toyhand': 'toy hand',
        'toykeys': 'toy keys',
        'toyplane': 'toy plane',
        'toywrench': 'toy wrench',
        'tractor': 'tractor',
        'train': 'train',
        'trashcan': 'trash can',
        'treadmill': 'treadmill',
        'tricycle': 'tricycle',
        'trophy': 'trophy',
        'trowel': 'trowel',
        'trumpet': 'trumpet',
        'trunk': 'trunk',
        'tube': 'tube',
        'turkey': 'turkey',
        'turtle': 'turtle',
        'tweezers': 'tweezers',
        'typewriter': 'typewriter',
        'umbrella': 'umbrella',
        'vacuum': 'vacuum',
        'vendingmachine': 'vending machine',
        'waffleiron': 'waffle iron',
        'walker': 'walker',
        'walkytalky': 'walkie-talkie',
        'walrus': 'walrus',
        'washer': 'washer',
        'watch': 'watch',
        'wateringcan': 'watering can',
        'waterjug': 'water jug',
        'weddingdress': 'wedding dress',
        'whale': 'whale',
        'wheelbarrow': 'wheelbarrow',
        'wheelchair': 'wheelchair',
        'windmill': 'windmill',
        'wineglass': 'wine glass',
        'wishwell': 'wishing well',
        'yacht': 'yacht',
        'yarn': 'yarn',
        'zebra': 'zebra'
    };