const image_list = ['images/barrel1.png','images/bottleopener1.png','images/clock1.png','images/clock2.png','images/clock3.png',
    'images/clock4.png','images/fishingrod1.png','images/fork1.png','images/fork2.png','images/fork3.png',
    'images/fork4.png','images/fridge1.png','images/handmirror1.png','images/hotairballoon1.png','images/ladder1.png',
    'images/measuringtape1.png','images/musicstand1.png','images/musicstand2.png','images/musicstand3.png',
    'images/musicstand4.png','images/pie1.png','images/pill1.png','images/plate1.png','images/plate2.png',
    'images/plate3.png','images/plate4.png','images/starfish1.png','images/starfish2.png','images/starfish3.png',
    'images/starfish4.png','images/tire1.png','images/tire2.png','images/tire3.png','images/tire4.png','images/tweezers1.png',
    'images/tweezers2.png','images/tweezers3.png','images/tweezers4.png','images/washer1.png','images/washer2.png',
    'images/washer3.png','images/washer4.png','images/wheelbarrow1.png','images/wheelbarrow2.png','images/wheelbarrow3.png',
    'images/wheelbarrow4.png','images/wheelchair1.png','images/wheelchair2.png','images/wheelchair3.png','images/wheelchair4.png',
    'images/abacus1.png','images/airpump1.png','images/airtank1.png','images/alligator1.png','images/anchor1.png',
    'images/antelope1.png','images/apple1.png','images/aquarium1.png','images/arch1.png','images/armchair1.png',
    'images/artichoke1.png','images/orangutan1.png','images/babyswing1.png','images/bagel1.png','images/balloon1.png',
    'images/banana1.png','images/bandaid1.png','images/barette1.png','images/baseballbat1.png','images/baseballcap1.png',
    'images/basket1.png','images/bat1.png','images/bathtub1.png','images/batteries1.png','images/beanbagchair1.png',
    'images/bed1.png','images/bee1.png','images/bell1.png','images/belt1.png','images/bench1.png','images/bunkbed1.png',
    'images/bicycle1.png','images/binoculars1.png','images/bishop1.png','images/blender1.png','images/blueberries1.png',
    'images/board1.png','images/whale1.png','images/book1.png','images/cooler1.png','images/bowtie1.png','images/box1.png',
    'images/bracelet1.png','images/bread1.png','images/briefcase1.png','images/broom1.png','images/buffalo1.png','images/building1.png',
    'images/bulldozer1.png','images/bunny1.png','images/butterfly1.png','images/button1.png','images/cabinet1.png','images/cake1.png',
    'images/calculator1.png','images/camel1.png','images/camera1.png','images/candle1.png','images/candy1.png','images/cane1.png',
    'images/canoe1.png','images/canopener1.png','images/canteloupe1.png','images/car1.png','images/carabener1.png','images/carrots1.png',
    'images/carseat1.png','images/cart1.png','images/cashregister1.png','images/cateringtray1.png','images/cherry1.png',
    'images/chisel1.png','images/clipboard1.png','images/candybar1.png','images/clothespin1.png','images/coconut1.png',
    'images/coffeemaker1.png','images/coffeepot1.png','images/coin1.png','images/comb1.png','images/compass1.png',
    'images/computer1.png','images/computermouse1.png','images/cone1.png','images/contactscase1.png','images/container1.png',
    'images/couger1.png','images/cow1.png','images/crab1.png','images/crayons1.png','images/crib1.png','images/croissant1.png',
    'images/crutches1.png','images/cupcake1.png','images/pingpongtable1.png','images/cuttingboard1.png','images/deer1.png',
    'images/die1.png','images/sealion1.png','images/dolphin1.png','images/bookcase1.png','images/dispenser1.png','images/dog1.png',
    'images/dollarbill1.png','images/dolly1.png','images/domino1.png','images/donut1.png','images/door1.png','images/dresser1.png',
    'images/dropbottle1.png','images/drum1.png','images/drumset1.png','images/dryer1.png','images/dumpster1.png','images/dustpan1.png',
    'images/earrings1.png','images/earth1.png','images/egg1.png','images/eggplant1.png','images/electricbass1.png','images/elephant1.png',
    'images/fan1.png','images/faucet1.png','images/feather1.png','images/filingcabinet1.png','images/fireextinguisher1.png',
    'images/fireplace1.png','images/firetrucktoy1.png','images/fishbowl1.png','images/flashlight1.png','images/flask1.png',
    'images/flipflops1.png','images/floppydisk1.png','images/flowerpot1.png','images/folder1.png','images/football1.png','images/forklift1.png',
    'images/fortunecookie1.png','images/fourwheeler1.png','images/fox1.png','images/frame1.png','images/frenchfries1.png','images/funnel1.png',
    'images/telephonebox1.png','images/gamecontroller1.png','images/gardeninghoe1.png','images/gaspump1.png','images/giftbag1.png','images/giraffe1.png',
    'images/glasses1.png','images/globe1.png','images/glove1.png','images/gnu1.png','images/goggles1.png','images/golfbag1.png','images/golfball1.png',
    'images/gong1.png','images/grapes1.png','images/grater1.png','images/grill1.png','images/grinder1.png','images/teak1.png','images/guitar1.png',
    'images/hairbrush1.png','images/hairdryer1.png','images/hammer1.png','images/hammock1.png','images/hanger1.png','images/harmonica1.png',
    'images/harp1.png','images/hat1.png','images/haybale1.png','images/headphones1.png','images/hedgehog1.png','images/marimba1.png',
    'images/highchair1.png','images/highlighter1.png','images/hippo1.png','images/holepunch1.png','images/honeystick1.png','images/horn1.png',
    'images/horse1.png','images/horseshoe1.png','images/hotdog1.png','images/hourglass1.png','images/hydrant1.png','images/icecream1.png',
    'images/igloo1.png','images/mailbox1.png','images/ironingboard1.png','images/juiceglass1.png','images/kayak1.png','images/kazoo1.png',
    'images/key1.png','images/keyboard1.png','images/keyboardkey1.png','images/knife1.png','images/ladybug1.png','images/lantern1.png',
    'images/laundrybasket1.png','images/lawnmower1.png','images/leaf1.png','images/licenseplate1.png','images/lifejacket1.png',
    'images/lifetube1.png','images/lightbulb1.png','images/lighter1.png','images/lighthouse1.png','images/lipstick1.png',
    'images/walrus1.png','images/lock1.png','images/lockbox1.png','images/log1.png','images/manatee1.png','images/matress1.png',
    'images/metalclip1.png','images/picnictable1.png','images/mitt1.png','images/mixer1.png','images/motorcycle1.png','images/muffin1.png',
    'images/mug1.png','images/nailpolish1.png','images/portapotty1.png','images/newspaperstand1.png','images/olive.png','images/ostrich1.png',
    'images/outhouse1.png','images/oven.png','images/pacifier1.png','images/padlock1.png','images/paintbrush.png','images/palmtree1.png',
    'images/paperclip.png','images/pasta1.png','images/patiotable1.png','images/pear1.png','images/peeler.png','images/pencil.png','images/penguin.png',
    'images/phone.png','images/piano1.png','images/pickle.png','images/pig1.png','images/piggybank.png','images/pipe1.png','images/pizza1.png',
    'images/pliers1.png','images/plunger1.png','images/polarbear.png','images/pooltable.png','images/pot1.png','images/potato.png','images/potatomasher1.png',
    'images/golfcart1.png','images/pretzel.png','images/pumpkinpie.png','images/qtips1.png','images/crochethook1.png','images/racquet.png','images/rake1.png',
    'images/razor1.png','images/recordplayer1.png','images/remote1.png','images/remover1.png','images/rhino.png','images/ring.png','images/rockingchair1.png',
    'images/ruler.png','images/saddle.png','images/safetypin.png','images/santahat1.png','images/gorilla1.png','images/schoolbag.png','images/scissors.png',
    'images/scooter1.png','images/screwdriver1.png','images/scroll1.png','images/scrubber1.png','images/seal1.png','images/seashell1.png','images/seats.png',
    'images/sewingmachine.png','images/sharpener1.png','images/sheep1.png','images/shelf.png','images/ship1.png','images/skateboard.png','images/bear1.png',
    'images/snail.png','images/snowflake.png','images/soapdish1.png','images/insect1.png','images/sock.png','images/yacht1.png','images/spinningwheel1.png',
    'images/spoon.png','images/spraybottle1.png','images/staircase1.png','images/stapler1.png','images/statue1.png','images/stonehome1.png','images/stoplight.png',
    'images/streetsign1.png','images/streetsweeper1.png','images/stroller1.png','images/suitcase1.png','images/swan.png','images/swimmingpool.png',
    'images/swimsuit1.png','images/teabag1.png','images/teapot1.png','images/telescope.png','images/tent.png','images/ticketstub1.png','images/tiger.png',
    'images/toilet.png','images/toiletpaper1.png','images/toiletseat1.png','images/tomato.png','images/tombstone1.png','images/tongs1.png','images/toothbrush1.png',
    'images/toy1.png','images/tractor1.png','images/train1.png','images/trashcan.png','images/tricycle1.png','images/trowel1.png','images/trumpet1.png','images/trunk.png',
    'images/tube1.png','images/llama1.png','images/turtle1.png','images/typewriter1.png','images/umbrella1.png','images/vacuum1.png','images/vendingmachine.png',
    'images/waffleiron.png','images/walker1.png','images/walkytalky1.png','images/watch1.png','images/kangaroo1.png','images/waterjug1.png','images/weddingdress1.png',
    'images/windmill1.png','images/wineglass1.png','images/wishwell1.png','images/yarn1.png','images/zebra1.png'];


    const categoryMappings = {
        'abacus': 'abacus',
        'airpump': 'air pump',
        'airtank': 'air tank',
        'alligator': 'alligator',
        'anchor': 'anchor',
        'antelope': 'antelope',
        'apple': 'apple',
        'aquarium': 'aquarium',
        'arch': 'arch',
        'armchair': 'armchair',
        'artichoke': 'artichoke',
        'babyswing': 'baby swing',
        'bagel': 'bagel',
        'balloon': 'balloon',
        'banana': 'banana',
        'bandaid': 'bandaid',
        'barette': 'barette',
        'barrel': 'barrel',
        'baseballbat': 'baseball bat',
        'baseballcap': 'baseball cap',
        'basket': 'basket',
        'bat': 'bat',
        'bathtub': 'bathtub',
        'batteries': 'batteries',
        'bear': 'bear',
        'beanbagchair': 'bean bag chair',
        'bed': 'bed',
        'bee': 'bee',
        'bell': 'bell',
        'belt': 'belt',
        'bench': 'bench',
        'bicycle': 'bicycle',
        'binoculars': 'binoculars',
        'bishop': 'bishop',
        'blender': 'blender',
        'blueberries': 'blueberries',
        'board': 'board',
        'book': 'book',
        'bookcase': 'bookcase',
        'bottleopener': 'bottle opener',
        'bowtie': 'bowtie',
        'box': 'box',
        'bracelet': 'bracelet',
        'bread': 'bread',
        'briefcase': 'briefcase',
        'broom': 'broom',
        'buffalo': 'buffalo',
        'building': 'building',
        'bulldozer': 'bulldozer',
        'bunkbed': 'bunk bed',
        'bunny': 'bunny',
        'butterfly': 'butterfly',
        'button': 'button',
        'cabinet': 'cabinet',
        'cake': 'cake',
        'calculator': 'calculator',
        'camel': 'camel',
        'camera': 'camera',
        'candle': 'candle',
        'candy': 'candy',
        'candybar': 'candy bar',
        'cane': 'cane',
        'canoe': 'canoe',
        'canopener': 'can opener',
        'canteloupe': 'canteloupe',
        'car': 'car',
        'carabener': 'carabiner',
        'carrots': 'carrots',
        'carseat': 'car seat',
        'cart': 'cart',
        'cashregister': 'cash register',
        'cateringtray': 'catering tray',
        'cherry': 'cherry',
        'chisel': 'chisel',
        'clipboard': 'clipboard',
        'clock': 'clock',
        'clothespin': 'clothespin',
        'coconut': 'coconut',
        'coffeemaker': 'coffee maker',
        'coffeepot': 'coffee pot',
        'coin': 'coin',
        'comb': 'comb',
        'compass': 'compass',
        'computer': 'computer',
        'computermouse': 'computer mouse',
        'cone': 'cone',
        'contactscase': 'contacts case',
        'container': 'container',
        'cooler': 'cooler',
        'couger': 'cougar',
        'cow': 'cow',
        'crab': 'crab',
        'crayons': 'crayons',
        'crib': 'crib',
        'crochethook': 'crochet hook',
        'croissant': 'croissant',
        'crutches': 'crutches',
        'cupcake': 'cupcake',
        'cuttingboard': 'cutting board',
        'deer': 'deer',
        'die': 'die',
        'dispenser': 'dispenser',
        'dog': 'dog',
        'dollarbill': 'dollar bill',
        'dolly': 'dolly',
        'dolphin': 'dolphin',
        'domino': 'domino',
        'donut': 'donut',
        'door': 'door',
        'dresser': 'dresser',
        'dropbottle': 'drop bottle',
        'drum': 'drum',
        'drumset': 'drum set',
        'dryer': 'dryer',
        'dumpster': 'dumpster',
        'dustpan': 'dustpan',
        'earrings': 'earrings',
        'earth': 'earth',
        'egg': 'egg',
        'eggplant': 'eggplant',
        'electricbass': 'electric bass',
        'elephant': 'elephant',
        'fan': 'fan',
        'faucet': 'faucet',
        'feather': 'feather',
        'filingcabinet': 'filing cabinet',
        'fireextinguisher': 'fire extinguisher',
        'fireplace': 'fireplace',
        'firetrucktoy': 'fire truck toy',
        'fishbowl': 'fish bowl',
        'fishingrod': 'fishing rod',
        'flashlight': 'flashlight',
        'flask': 'flask',
        'flipflops': 'flip flops',
        'floppydisk': 'floppy disk',
        'flowerpot': 'flower pot',
        'folder': 'folder',
        'football': 'football',
        'fork': 'fork',
        'forklift': 'forklift',
        'fortunecookie': 'fortune cookie',
        'fourwheeler': 'four wheeler',
        'fox': 'fox',
        'frame': 'frame',
        'frenchfries': 'french fries',
        'fridge': 'fridge',
        'funnel': 'funnel',
        'gamecontroller': 'game controller',
        'gardeninghoe': 'gardening hoe',
        'gaspump': 'gas pump',
        'giftbag': 'gift bag',
        'giraffe': 'giraffe',
        'glasses': 'glasses',
        'globe': 'globe',
        'glove': 'glove',
        'gnu': 'gnu',
        'goggles': 'goggles',
        'golfbag': 'golf bag',
        'golfball': 'golf ball',
        'golfcart': 'golf cart',
        'gong': 'gong',
        'gorilla': 'gorilla',
        'grapes': 'grapes',
        'grater': 'grater',
        'grill': 'grill',
        'grinder': 'grinder',
        'guitar': 'guitar',
        'hairbrush': 'hair brush',
        'hairdryer': 'hair dryer',
        'hammer': 'hammer',
        'hammock': 'hammock',
        'handmirror': 'hand mirror',
        'hanger': 'hanger',
        'harmonica': 'harmonica',
        'harp': 'harp',
        'hat': 'hat',
        'haybale': 'hay bale',
        'headphones': 'headphones',
        'hedgehog': 'hedgehog',
        'highchair': 'high chair',
        'highlighter': 'highlighter',
        'hippo': 'hippo',
        'holepunch': 'hole punch',
        'honeystick': 'honey stick',
        'horn': 'horn',
        'horse': 'horse',
        'horseshoe': 'horseshoe',
        'hotairballoon': 'hot air balloon',
        'hotdog': 'hot dog',
        'hourglass': 'hourglass',
        'hydrant': 'hydrant',
        'icecream': 'ice cream',
        'igloo': 'igloo',
        'insect': 'insect',
        'ironingboard': 'ironing board',
        'juiceglass': 'juice glass',
        'kangaroo': 'kangaroo',
        'kayak': 'kayak',
        'kazoo': 'kazoo',
        'key': 'key',
        'keyboard': 'keyboard',
        'keyboardkey': 'keyboard key',
        'knife': 'knife',
        'ladder': 'ladder',
        'ladybug': 'ladybug',
        'lantern': 'lantern',
        'laundrybasket': 'laundry basket',
        'lawnmower': 'lawn mower',
        'leaf': 'leaf',
        'licenseplate': 'license plate',
        'lifejacket': 'life jacket',
        'lifetube': 'life tube',
        'lightbulb': 'light bulb',
        'lighter': 'lighter',
        'lighthouse': 'lighthouse',
        'lipstick': 'lipstick',
        'llama': 'llama',
        'lock': 'lock',
        'lockbox': 'lock box',
        'log': 'log',
        'mailbox': 'mailbox',
        'manatee': 'manatee',
        'marimba': 'marimba',
        'matress': 'mattress',
        'measuringtape': 'measuring tape',
        'metalclip': 'metal clip',
        'mitt': 'mitt',
        'mixer': 'mixer',
        'motorcycle': 'motorcycle',
        'muffin': 'muffin',
        'mug': 'mug',
        'musicstand': 'music stand',
        'nailpolish': 'nail polish',
        'newspaperstand': 'newspaper stand',
        'olive': 'olive',
        'orangutan': 'orangutan',
        'ostrich': 'ostrich',
        'outhouse': 'outhouse',
        'oven': 'oven',
        'pacifier': 'pacifier',
        'padlock': 'padlock',
        'paintbrush': 'paintbrush',
        'palmtree': 'palm tree',
        'paperclip': 'paper clip',
        'pasta': 'pasta',
        'patiotable': 'patio table',
        'pear': 'pear',
        'peeler': 'peeler',
        'pencil': 'pencil',
        'penguin': 'penguin',
        'phone': 'phone',
        'piano': 'piano',
        'pickle': 'pickle',
        'picnictable': 'picnic table',
        'pie': 'pie',
        'pig': 'pig',
        'piggybank': 'piggy bank',
        'pill': 'pill',
        'pingpongtable': 'ping pong table',
        'pipe': 'pipe',
        'pizza': 'pizza',
        'plate': 'plate',
        'pliers': 'pliers',
        'plunger': 'plunger',
        'polarbear': 'polar bear',
        'pooltable': 'pool table',
        'portapotty': 'porta potty',
        'pot': 'pot',
        'potato': 'potato',
        'potatomasher': 'potato masher',
        'pretzel': 'pretzel',
        'pumpkinpie': 'pumpkin pie',
        'qtips': 'qtips',
        'racquet': 'racquet',
        'rake': 'rake',
        'razor': 'razor',
        'recordplayer': 'record player',
        'remote': 'remote',
        'remover': 'remover',
        'rhino': 'rhino',
        'ring': 'ring',
        'rockingchair': 'rocking chair',
        'ruler': 'ruler',
        'saddle': 'saddle',
        'safetypin': 'safety pin',
        'santahat': 'santa hat',
        'schoolbag': 'school bag',
        'scissors': 'scissors',
        'scooter': 'scooter',
        'screwdriver': 'screwdriver',
        'scroll': 'scroll',
        'scrubber': 'scrubber',
        'seal': 'seal',
        'sealion': 'sea lion',
        'seashell': 'seashell',
        'seats': 'seats',
        'sewingmachine': 'sewing machine',
        'sharpener': 'sharpener',
        'sheep': 'sheep',
        'shelf': 'shelf',
        'ship': 'ship',
        'skateboard': 'skateboard',
        'snail': 'snail',
        'snowflake': 'snowflake',
        'soapdish': 'soap dish',
        'sock': 'sock',
        'spinningwheel': 'spinning wheel',
        'spoon': 'spoon',
        'spraybottle': 'spray bottle',
        'staircase': 'staircase',
        'stapler': 'stapler',
        'starfish': 'starfish',
        'statue': 'statue',
        'stonehome': 'stone home',
        'stoplight': 'stop light',
        'streetsign': 'street sign',
        'streetsweeper': 'street sweeper',
        'stroller': 'stroller',
        'suitcase': 'suitcase',
        'swan': 'swan',
        'swimmingpool': 'swimming pool',
        'swimsuit': 'swimsuit',
        'teabag': 'tea bag',
        'teak': 'teak',
        'teapot': 'teapot',
        'telescope': 'telescope',
        'telephonebox': 'telephone box',
        'tent': 'tent',
        'ticketstub': 'ticket stub',
        'tiger': 'tiger',
        'tire': 'tire',
        'toilet': 'toilet',
        'toiletpaper': 'toilet paper',
        'toiletseat': 'toilet seat',
        'tomato': 'tomato',
        'tombstone': 'tombstone',
        'tongs': 'tongs',
        'toothbrush': 'toothbrush',
        'toy': 'toy',
        'tractor': 'tractor',
        'train': 'train',
        'trashcan': 'trash can',
        'tricycle': 'tricycle',
        'trowel': 'trowel',
        'trumpet': 'trumpet',
        'trunk': 'trunk',
        'tube': 'tube',
        'turtle': 'turtle',
        'tweezers': 'tweezers',
        'typewriter': 'typewriter',
        'umbrella': 'umbrella',
        'vacuum': 'vacuum',
        'vendingmachine': 'vending machine',
        'waffleiron': 'waffle iron',
        'walker': 'walker',
        'walkytalky': 'walky talky',
        'walrus': 'walrus',
        'washer': 'washer',
        'watch': 'watch',
        'waterjug': 'water jug',
        'weddingdress': 'wedding dress',
        'whale': 'whale',
        'wheelbarrow': 'wheelbarrow',
        'wheelchair': 'wheelchair',
        'windmill': 'windmill',
        'wineglass': 'wine glass',
        'wishwell': 'wishing well',
        'yacht': 'yacht',
        'yarn': 'yarn',
        'zebra': 'zebra'
    };