const image_list = ['images/barrel1.png','images/bottleopener1.png','images/clock1.png','images/clock2.png','images/clock3.png',
    'images/clock4.png','images/fishingrod1.png','images/fork1.png','images/fork2.png','images/fork3.png',
    'images/fork4.png','images/fridge1.png','images/handmirror1.png','images/hotairballoon1.png','images/ladder1.png',
    'images/measuringtape1.png','images/musicstand1.png','images/musicstand2.png','images/musicstand3.png',
    'images/musicstand4.png','images/pie1.png','images/pill1.png','images/plate1.png','images/plate2.png',
    'images/plate3.png','images/plate4.png','images/starfish1.png','images/starfish2.png','images/starfish3.png',
    'images/starfish4.png','images/tire1.png','images/tire2.png','images/tire3.png','images/tire4.png','images/tweezers1.png',
    'images/tweezers2.png','images/tweezers3.png','images/tweezers4.png','images/washer1.png','images/washer2.png',
    'images/washer3.png','images/washer4.png','images/wheelbarrow1.png','images/wheelbarrow2.png','images/wheelbarrow3.png',
    'images/wheelbarrow4.png','images/wheelchair1.png','images/wheelchair2.png','images/wheelchair3.png','images/wheelchair4.png',
    'images/abacus1.png','images/airpump1.png','images/airtank1.png','images/alligator1.png','images/anchor1.png',
    'images/antelope1.png','images/apple1.png','images/aquarium1.png','images/arch1.png','images/armchair1.png',
    'images/artichoke1.png','images/orangutan1.png','images/babyswing1.png','images/bagel1.png','images/balloon1.png',
    'images/banana1.png','images/bandaid1.png','images/barette1.png','images/baseballbat1.png','images/baseballcap1.png',
    'images/basket1.png','images/bat1.png','images/bathtub1.png','images/batteries1.png','images/beanbagchair1.png',
    'images/bed1.png','images/bee1.png','images/bell1.png','images/belt1.png','images/bench1.png','images/bunkbed1.png',
    'images/bicycle1.png','images/binoculars1.png','images/bishop1.png','images/blender1.png','images/blueberries1.png',
    'images/board1.png','images/whale1.png','images/book1.png','images/cooler1.png','images/bowtie1.png','images/box1.png',
    'images/bracelet1.png','images/bread1.png','images/briefcase1.png','images/broom1.png','images/buffalo1.png','images/building1.png',
    'images/bulldozer1.png','images/bunny1.png','images/butterfly1.png','images/button1.png','images/cabinet1.png','images/cake1.png',
    'images/calculator1.png','images/camel1.png','images/camera1.png','images/candle1.png','images/candy1.png','images/cane1.png',
    'images/canoe1.png','images/canopener1.png','images/canteloupe1.png','images/car1.png','images/carabener1.png','images/carrots1.png',
    'images/carseat1.png','images/cart1.png','images/cashregister1.png','images/cateringtray1.png','images/cherry1.png',
    'images/chisel1.png','images/clipboard1.png','images/candybar1.png','images/clothespin1.png','images/coconut1.png',
    'images/coffeemaker1.png','images/coffeepot1.png','images/coin1.png','images/comb1.png','images/compass1.png',
    'images/computer1.png','images/computermouse1.png','images/cone1.png','images/contactscase1.png','images/container1.png',
    'images/couger1.png','images/cow1.png','images/crab1.png','images/crayons1.png','images/crib1.png','images/croissant1.png',
    'images/crutches1.png','images/cupcake1.png','images/pingpongtable1.png','images/cuttingboard1.png','images/deer1.png',
    'images/die1.png','images/sealion1.png','images/dolphin1.png','images/bookcase1.png','images/dispenser1.png','images/dog1.png',
    'images/dollarbill1.png','images/dolly1.png','images/domino1.png','images/donut1.png','images/door1.png','images/dresser1.png',
    'images/dropbottle1.png','images/drum1.png','images/drumset1.png','images/dryer1.png','images/dumpster1.png','images/dustpan1.png',
    'images/earrings1.png','images/earth1.png','images/egg1.png','images/eggplant1.png','images/electricbass1.png','images/elephant1.png',
    'images/fan1.png','images/faucet1.png','images/feather1.png','images/filingcabinet1.png','images/fireextinguisher1.png',
    'images/fireplace1.png','images/firetrucktoy1.png','images/fishbowl1.png','images/flashlight1.png','images/flask1.png',
    'images/flipflops1.png','images/floppydisk1.png','images/flowerpot1.png','images/folder1.png','images/football1.png','images/forklift1.png',
    'images/fortunecookie1.png','images/fourwheeler1.png','images/fox1.png','images/frame1.png','images/frenchfries1.png','images/funnel1.png',
    'images/telephonebox1.png','images/gamecontroller1.png','images/gardeninghoe1.png','images/gaspump1.png','images/giftbag1.png','images/giraffe1.png',
    'images/glasses1.png','images/globe1.png','images/glove1.png','images/gnu1.png','images/goggles1.png','images/golfbag1.png','images/golfball1.png',
    'images/gong1.png','images/grapes1.png','images/grater1.png','images/grill1.png','images/grinder1.png','images/teak1.png','images/guitar1.png',
    'images/hairbrush1.png','images/hairdryer1.png','images/hammer1.png','images/hammock1.png','images/hanger1.png','images/harmonica1.png',
    'images/harp1.png','images/hat1.png','images/haybale1.png','images/headphones1.png','images/hedgehog1.png','images/marimba1.png',
    'images/highchair1.png','images/highlighter1.png','images/hippo1.png','images/holepunch1.png','images/honeystick1.png','images/horn1.png',
    'images/horse1.png','images/horseshoe1.png','images/hotdog1.png','images/hourglass1.png','images/hydrant1.png','images/icecream1.png',
    'images/igloo1.png','images/mailbox1.png','images/ironingboard1.png','images/juiceglass1.png','images/kayak1.png','images/kazoo1.png',
    'images/key1.png','images/keyboard1.png','images/keyboardkey1.png','images/knife1.png','images/ladybug1.png','images/lantern1.png',
    'images/laundrybasket1.png','images/lawnmower1.png','images/leaf1.png','images/licenseplate1.png','images/lifejacket1.png',
    'images/lifetube1.png','images/lightbulb1.png','images/lighter1.png','images/lighthouse1.png','images/lipstick1.png',
    'images/walrus1.png','images/lock1.png','images/lockbox1.png','images/log1.png','images/manatee1.png','images/matress1.png',
    'images/metalclip1.png','images/picnictable1.png','images/mitt1.png','images/mixer1.png','images/motorcycle1.png','images/muffin1.png',
    'images/mug1.png','images/nailpolish1.png','images/portapotty1.png','images/newspaperstand1.png','images/olive.png','images/ostrich1.png',
    'images/outhouse1.png','images/oven.png','images/pacifier1.png','images/padlock1.png','images/paintbrush.png','images/palmtree1.png',
    'images/paperclip.png','images/pasta1.png','images/patiotable1.png','images/pear1.png','images/peeler.png','images/pencil.png','images/penguin.png',
    'images/phone.png','images/piano1.png','images/pickle.png','images/pig1.png','images/piggybank.png','images/pipe1.png','images/pizza1.png',
    'images/pliers1.png','images/plunger1.png','images/polarbear.png','images/pooltable.png','images/pot1.png','images/potato.png','images/potatomasher1.png',
    'images/golfcart1.png','images/pretzel.png','images/pumpkinpie.png','images/qtips1.png','images/crochethook1.png','images/racquet.png','images/rake1.png',
    'images/razor1.png','images/recordplayer1.png','images/remote1.png','images/remover1.png','images/rhino.png','images/ring.png','images/rockingchair1.png',
    'images/ruler.png','images/saddle.png','images/safetypin.png','images/santahat1.png','images/gorilla1.png','images/schoolbag.png','images/scissors.png',
    'images/scooter1.png','images/screwdriver1.png','images/scroll1.png','images/scrubber1.png','images/seal1.png','images/seashell1.png','images/seats.png',
    'images/sewingmachine.png','images/sharpener1.png','images/sheep1.png','images/shelf.png','images/ship1.png','images/skateboard.png','images/bear1.png',
    'images/snail.png','images/snowflake.png','images/soapdish1.png','images/insect1.png','images/sock.png','images/yacht1.png','images/spinningwheel1.png',
    'images/spoon.png','images/spraybottle1.png','images/staircase1.png','images/stapler1.png','images/statue1.png','images/stonehome1.png','images/stoplight.png',
    'images/streetsign1.png','images/streetsweeper1.png','images/stroller1.png','images/suitcase1.png','images/swan.png','images/swimmingpool.png',
    'images/swimsuit1.png','images/teabag1.png','images/teapot1.png','images/telescope.png','images/tent.png','images/ticketstub1.png','images/tiger.png',
    'images/toilet.png','images/toiletpaper1.png','images/toiletseat1.png','images/tomato.png','images/tombstone1.png','images/tongs1.png','images/toothbrush1.png',
    'images/toy1.png','images/tractor1.png','images/train1.png','images/trashcan.png','images/tricycle1.png','images/trowel1.png','images/trumpet1.png','images/trunk.png',
    'images/tube1.png','images/llama1.png','images/turtle1.png','images/typewriter1.png','images/umbrella1.png','images/vacuum1.png','images/vendingmachine.png',
    'images/waffleiron.png','images/walker1.png','images/walkytalky1.png','images/watch1.png','images/kangaroo1.png','images/waterjug1.png','images/weddingdress1.png',
    'images/windmill1.png','images/wineglass1.png','images/wishwell1.png','images/yarn1.png','images/zebra1.png'];


const categoryMappings = {
    'abacus': 'abacuses',
    'airpump': 'air pumps',
    'airtank': 'air tanks',
    'alligator': 'alligators',
    'anchor': 'anchors',
    'antelope': 'antelopes',
    'apple': 'apples',
    'aquarium': 'aquariums',
    'arch': 'arches',
    'armchair': 'armchairs',
    'artichoke': 'artichokes',
    'babyswing': 'baby swings',
    'bagel': 'bagels',
    'balloon': 'balloons',
    'banana': 'bananas',
    'bandaid': 'bandaids',
    'barette': 'barettes',
    'barrel': 'barrels',
    'baseballbat': 'baseball bats',
    'baseballcap': 'baseball caps',
    'basket': 'baskets',
    'bat': 'bats',
    'bathtub': 'bathtubs',
    'batteries': 'batteries',
    'bear': 'bears',
    'beanbagchair': 'bean bag chairs',
    'bed': 'beds',
    'bee': 'bees',
    'bell': 'bells',
    'belt': 'belts',
    'bench': 'benches',
    'bicycle': 'bicycles',
    'binoculars': 'binoculars',
    'bishop': 'bishops',
    'blender': 'blenders',
    'blueberries': 'blueberries',
    'board': 'boards',
    'book': 'books',
    'bookcase': 'bookcases',
    'bottleopener': 'bottle openers',
    'bowtie': 'bowties',
    'box': 'boxes',
    'bracelet': 'bracelets',
    'bread': 'breads',
    'briefcase': 'briefcases',
    'broom': 'brooms',
    'buffalo': 'buffalo',
    'building': 'buildings',
    'bulldozer': 'bulldozers',
    'bunkbed': 'bunk beds',
    'bunny': 'bunnies',
    'butterfly': 'butterflies',
    'button': 'buttons',
    'cabinet': 'cabinets',
    'cake': 'cakes',
    'calculator': 'calculators',
    'camel': 'camels',
    'camera': 'cameras',
    'candle': 'candles',
    'candy': 'candies',
    'candybar': 'candy bars',
    'cane': 'canes',
    'canoe': 'canoes',
    'canopener': 'can openers',
    'canteloupe': 'canteloupes',
    'car': 'cars',
    'carabener': 'carabiners',
    'carrots': 'carrots',
    'carseat': 'car seats',
    'cart': 'carts',
    'cashregister': 'cash registers',
    'cateringtray': 'catering trays',
    'cherry': 'cherries',
    'chisel': 'chisels',
    'clipboard': 'clipboards',
    'clock': 'clocks',
    'clothespin': 'clothespins',
    'coconut': 'coconuts',
    'coffeemaker': 'coffee makers',
    'coffeepot': 'coffee pots',
    'coin': 'coins',
    'comb': 'combs',
    'compass': 'compasses',
    'computer': 'computers',
    'computermouse': 'computer mice',
    'cone': 'cones',
    'contactscase': 'contacts cases',
    'container': 'containers',
    'cooler': 'coolers',
    'couger': 'cougars',
    'cow': 'cows',
    'crab': 'crabs',
    'crayons': 'crayons',
    'crib': 'cribs',
    'crochethook': 'crochet hooks',
    'croissant': 'croissants',
    'crutches': 'crutches',
    'cupcake': 'cupcakes',
    'cuttingboard': 'cutting boards',
    'deer': 'deer',
    'die': 'dice',
    'dispenser': 'dispensers',
    'dog': 'dogs',
    'dollarbill': 'dollar bills',
    'dolly': 'dollies',
    'dolphin': 'dolphins',
    'domino': 'dominoes',
    'donut': 'donuts',
    'door': 'doors',
    'dresser': 'dressers',
    'dropbottle': 'drop bottles',
    'drum': 'drums',
    'drumset': 'drum sets',
    'dryer': 'dryers',
    'dumpster': 'dumpsters',
    'dustpan': 'dustpans',
    'earrings': 'earrings',
    'earth': 'earths',
    'egg': 'eggs',
    'eggplant': 'eggplants',
    'electricbass': 'electric basses',
    'elephant': 'elephants',
    'fan': 'fans',
    'faucet': 'faucets',
    'feather': 'feathers',
    'filingcabinet': 'filing cabinets',
    'fireextinguisher': 'fire extinguishers',
    'fireplace': 'fireplaces',
    'firetrucktoy': 'fire truck toys',
    'fishbowl': 'fish bowls',
    'fishingrod': 'fishing rods',
    'flashlight': 'flashlights',
    'flask': 'flasks',
    'flipflops': 'flip flops',
    'floppydisk': 'floppy disks',
    'flowerpot': 'flower pots',
    'folder': 'folders',
    'football': 'footballs',
    'fork': 'forks',
    'forklift': 'forklifts',
    'fortunecookie': 'fortune cookies',
    'fourwheeler': 'four wheelers',
    'fox': 'foxes',
    'frame': 'frames',
    'frenchfries': 'french fries',
    'fridge': 'fridges',
    'funnel': 'funnels',
    'gamecontroller': 'game controllers',
    'gardeninghoe': 'gardening hoes',
    'gaspump': 'gas pumps',
    'giftbag': 'gift bags',
    'giraffe': 'giraffes',
    'glasses': 'glasses',
    'globe': 'globes',
    'glove': 'gloves',
    'gnu': 'gnus',
    'goggles': 'goggles',
    'golfbag': 'golf bags',
    'golfball': 'golf balls',
    'golfcart': 'golf carts',
    'gong': 'gongs',
    'gorilla': 'gorillas',
    'grapes': 'grapes',
    'grater': 'graters',
    'grill': 'grills',
    'grinder': 'grinders',
    'guitar': 'guitars',
    'hairbrush': 'hair brushes',
    'hairdryer': 'hair dryers',
    'hammer': 'hammers',
    'hammock': 'hammocks',
    'handmirror': 'hand mirrors',
    'hanger': 'hangers',
    'harmonica': 'harmonicas',
    'harp': 'harps',
    'hat': 'hats',
    'haybale': 'hay bales',
    'headphones': 'headphones',
    'hedgehog': 'hedgehogs',
    'highchair': 'high chairs',
    'highlighter': 'highlighters',
    'hippo': 'hippos',
    'holepunch': 'hole punches',
    'honeystick': 'honey sticks',
    'horn': 'horns',
    'horse': 'horses',
    'horseshoe': 'horseshoes',
    'hotairballoon': 'hot air balloons',
    'hotdog': 'hot dogs',
    'hourglass': 'hourglasses',
    'hydrant': 'hydrants',
    'icecream': 'ice creams',
    'igloo': 'igloos',
    'insect': 'insects',
    'ironingboard': 'ironing boards',
    'juiceglass': 'juice glasses',
    'kangaroo': 'kangaroos',
    'kayak': 'kayaks',
    'kazoo': 'kazoos',
    'key': 'keys',
    'keyboard': 'keyboards',
    'keyboardkey': 'keyboard keys',
    'knife': 'knives',
    'ladder': 'ladders',
    'ladybug': 'ladybugs',
    'lantern': 'lanterns',
    'laundrybasket': 'laundry baskets',
    'lawnmower': 'lawn mowers',
    'leaf': 'leaves',
    'licenseplate': 'license plates',
    'lifejacket': 'life jackets',
    'lifetube': 'life tubes',
    'lightbulb': 'light bulbs',
    'lighter': 'lighters',
    'lighthouse': 'lighthouses',
    'lipstick': 'lipsticks',
    'llama': 'llamas',
    'lock': 'locks',
    'lockbox': 'lock boxes',
    'log': 'logs',
    'mailbox': 'mailboxes',
    'manatee': 'manatees',
    'marimba': 'marimbas',
    'matress': 'mattresses',
    'measuringtape': 'measuring tapes',
    'metalclip': 'metal clips',
    'mitt': 'mitts',
    'mixer': 'mixers',
    'motorcycle': 'motorcycles',
    'muffin': 'muffins',
    'mug': 'mugs',
    'musicstand': 'music stands',
    'nailpolish': 'nail polishes',
    'newspaperstand': 'newspaper stands',
    'olive': 'olives',
    'orangutan': 'orangutans',
    'ostrich': 'ostriches',
    'outhouse': 'outhouses',
    'oven': 'ovens',
    'pacifier': 'pacifiers',
    'padlock': 'padlocks',
    'paintbrush': 'paintbrushes',
    'palmtree': 'palm trees',
    'paperclip': 'paper clips',
    'pasta': 'pastas',
    'patiotable': 'patio tables',
    'pear': 'pears',
    'peeler': 'peelers',
    'pencil': 'pencils',
    'penguin': 'penguins',
    'phone': 'phones',
    'piano': 'pianos',
    'pickle': 'pickles',
    'picnictable': 'picnic tables',
    'pie': 'pies',
    'pig': 'pigs',
    'piggybank': 'piggy banks',
    'pill': 'pills',
    'pingpongtable': 'ping pong tables',
    'pipe': 'pipes',
    'pizza': 'pizzas',
    'plate': 'plates',
    'pliers': 'pliers',
    'plunger': 'plungers',
    'polarbear': 'polar bears',
    'pooltable': 'pool tables',
    'portapotty': 'porta potties',
    'pot': 'pots',
    'potato': 'potatoes',
    'potatomasher': 'potato mashers',
    'pretzel': 'pretzels',
    'pumpkinpie': 'pumpkin pies',
    'qtips': 'qtips',
    'racquet': 'racquets',
    'rake': 'rakes',
    'razor': 'razors',
    'recordplayer': 'record players',
    'remote': 'remotes',
    'remover': 'removers',
    'rhino': 'rhinos',
    'ring': 'rings',
    'rockingchair': 'rocking chairs',
    'ruler': 'rulers',
    'saddle': 'saddles',
    'safetypin': 'safety pins',
    'santahat': 'santa hats',
    'schoolbag': 'school bags',
    'scissors': 'scissors',
    'scooter': 'scooters',
    'screwdriver': 'screwdrivers',
    'scroll': 'scrolls',
    'scrubber': 'scrubbers',
    'seal': 'seals',
    'sealion': 'sea lions',
    'seashell': 'seashells',
    'seats': 'seats',
    'sewingmachine': 'sewing machines',
    'sharpener': 'sharpeners',
    'sheep': 'sheep',
    'shelf': 'shelves',
    'ship': 'ships',
    'skateboard': 'skateboards',
    'snail': 'snails',
    'snowflake': 'snowflakes',
    'soapdish': 'soap dishes',
    'sock': 'socks',
    'spinningwheel': 'spinning wheels',
    'spoon': 'spoons',
    'spraybottle': 'spray bottles',
    'staircase': 'staircases',
    'stapler': 'staplers',
    'starfish': 'starfish',
    'statue': 'statues',
    'stonehome': 'stone homes',
    'stoplight': 'stop lights',
    'streetsign': 'street signs',
    'streetsweeper': 'street sweepers',
    'stroller': 'strollers',
    'suitcase': 'suitcases',
    'swan': 'swans',
    'swimmingpool': 'swimming pools',
    'swimsuit': 'swimsuits',
    'teabag': 'tea bags',
    'teak': 'teaks',
    'teapot': 'teapots',
    'telescope': 'telescopes',
    'telephonebox': 'telephone boxes',
    'tent': 'tents',
    'ticketstub': 'ticket stubs',
    'tiger': 'tigers',
    'tire': 'tires',
    'toilet': 'toilets',
    'toiletpaper': 'toilet paper',
    'toiletseat': 'toilet seats',
    'tomato': 'tomatoes',
    'tombstone': 'tombstones',
    'tongs': 'tongs',
    'toothbrush': 'toothbrushes',
    'toy': 'toys',
    'tractor': 'tractors',
    'train': 'trains',
    'trashcan': 'trash cans',
    'tricycle': 'tricycles',
    'trowel': 'trowels',
    'trumpet': 'trumpets',
    'trunk': 'trunks',
    'tube': 'tubes',
    'turtle': 'turtles',
    'tweezers': 'tweezers',
    'typewriter': 'typewriters',
    'umbrella': 'umbrellas',
    'vacuum': 'vacuums',
    'vendingmachine': 'vending machines',
    'waffleiron': 'waffle irons',
    'walker': 'walkers',
    'walkytalky': 'walky talkies',
    'walrus': 'walruses',
    'washer': 'washers',
    'watch': 'watches',
    'waterjug': 'water jugs',
    'weddingdress': 'wedding dresses',
    'whale': 'whales',
    'wheelbarrow': 'wheelbarrows',
    'wheelchair': 'wheelchairs',
    'windmill': 'windmills',
    'wineglass': 'wine glasses',
    'wishwell': 'wishing wells',
    'yacht': 'yachts',
    'yarn': 'yarns',
    'zebra': 'zebras'
};
